name: twaf
version: 1.0.0+1
publish_to: none
description: A new Flutter project.
environment: 
  sdk: '>=2.15.0-31.0.dev <3.0.0'

dependencies: 
  flutter: 
    sdk: flutter
  cupertino_icons: ^1.0.2
  get: 4.6.1
  flutter_svg: ^0.22.0
  get_storage: ^2.0.3
  adaptive_action_sheet: ^2.0.1
  badges: ^2.0.2
  flutter_datetime_picker: ^1.4.1
  floating_bottom_navigation_bar: ^1.5.2
  modal_bottom_sheet: ^2.0.0
  http: ^0.13.3
  card_swiper: ^2.0.1
  status_change: ^2.0.0
  # timelines: ^0.1.0
  flutter_timeline: ^0.3.0
  

 
dev_dependencies: 
  lints: 1.0.1
  flutter_test: 
    sdk: flutter
#   flutter_native_splash: ^1.3.3 

# flutter_native_splash:
#   color: "#ffffff"
#   image: assets/splash.png
#   andriod: true
#   ios: true

flutter: 
  uses-material-design: true

  assets:
    - assets/
    - assets/Icons/
    - assets/fonts/
  fonts:
    - family: AppIcons
      fonts:
        - asset: assets/fonts/AppIcons.ttf
    - family: Almarai
      fonts:
        - asset: assets/fonts/Almarai-Bold.ttf
        - asset: assets/fonts/Almarai-Regular.ttf
        - asset: assets/fonts/Almarai-Light.ttf
        - asset: assets/fonts/Almarai-ExtraBold.ttf